version: "3"
services:
  app:
    build: .
    volumes:
      - "./:/usr/src/app"
    env_file:
      - .env
    ports:
      - "${API_PORT}:${API_PORT}"
    depends_on:
      - database
  database:
    image: mysql
    restart: always
    platform: linux/amd64 # for M1 chips only (macbook)
    logging:
      driver: "none"
    env_file: ./.env
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    ports:
      - $MYSQL_PORT:$MYSQL_PORT
    volumes:
      - db-config:/etc/mysql
      - db-data:/var/lib/mysql
      - ./db/backup/files/:/data_backup/data
volumes:
  db-config:
  db-data:
